"use strict";(()=>{var e={};e.id=1568,e.ids=[1568],e.modules={145:e=>{e.exports=require("next/dist/compiled/next-server/pages-api.runtime.prod.js")},885:(e,t,a)=>{a.r(t),a.d(t,{config:()=>l,default:()=>o,routeModule:()=>p});var r={};a.r(r),a.d(r,{default:()=>handler});var n=a(1802),i=a(7153),s=a(6249);let{getPool:u}=a(6541);async function handler(e,t){let{email:a}=e.query||{},r=process.env.EXTERNAL_PRESTATIONS_URL;if(r)try{let e=new URL(r);a&&e.searchParams.set("email",a);let n=await fetch(e.toString()),i=await n.json();return t.status(n.ok?200:502).json({prestations:i.prestations||i||[]})}catch(e){return console.error("Proxy to external prestations failed",e),t.status(502).json({error:"External service unavailable"})}let n=u();try{let e;if(!a)return t.status(200).json({prestations:[]});let[r]=await n.query("SELECT id FROM users WHERE LOWER(email) = ?",[(a||"").toLowerCase()]);if(!r||0===r.length)return t.status(200).json({prestations:[]});let i=r[0].id,s=`SELECT p.id, p.date, p.pay_type, p.remuneration_infi, p.remuneration_med, p.status, p.analytic_id,
            p.garde_hours, p.sortie_hours, p.overtime_hours, p.hours_actual,
            p.expense_amount, p.expense_comment, p.pdf_url, p.request_ref, p.invoice_number,
            an.code AS analytic_code, an.name AS analytic_name
             FROM prestations p
               LEFT JOIN analytics an ON p.analytic_id = an.id
               WHERE p.user_id = ?
               ORDER BY p.date DESC, p.id DESC
               LIMIT 500`;try{let t=await n.query(s,[i]);e=t[0]||t}catch(r){console.warn("[api/prestations] primary query failed, retrying without expense columns",r&&r.code);let t=`SELECT p.id, p.date, p.pay_type, p.remuneration_infi, p.remuneration_med, p.status,
                        an.code AS analytic_code, an.name AS analytic_name
                 FROM prestations p
                 LEFT JOIN analytics an ON p.analytic_id = an.id
                 WHERE p.user_id = ?
                 ORDER BY p.date DESC, p.id DESC
                 LIMIT 500`,a=await n.query(t,[i]);e=a[0]||a}let u=(e||[]).map(e=>{let t=null;return e.date&&(t=e.date instanceof Date?e.date.toISOString().slice(0,10):"string"==typeof e.date?e.date.slice(0,10):String(e.date)),{id:e.id,date:t,pay_type:e.pay_type||null,analytic_id:e.analytic_id||null,request_ref:e.request_ref||null,invoice_number:e.invoice_number||null,garde_hours:null!=e.garde_hours?Number(e.garde_hours):0,sortie_hours:null!=e.sortie_hours?Number(e.sortie_hours):0,overtime_hours:null!=e.overtime_hours?Number(e.overtime_hours):0,hours_actual:null!=e.hours_actual?Number(e.hours_actual):0,remuneration_infi:null!=e.remuneration_infi?Number(e.remuneration_infi):null,remuneration_med:null!=e.remuneration_med?Number(e.remuneration_med):null,expense_amount:null!=e.expense_amount?Number(e.expense_amount):null,expense_comment:e.expense_comment||null,pdf_url:e.pdf_url||null,status:e.status||null,analytic_code:e.analytic_code||null,analytic_name:e.analytic_name||e.analytic_code||null}});return t.status(200).json({prestations:u})}catch(e){return console.error("[api/prestations] db error",e&&e.message),t.status(500).json({error:"db_error"})}}let o=(0,s.l)(r,"default"),l=(0,s.l)(r,"config"),p=new n.PagesAPIRouteModule({definition:{kind:i.x.PAGES_API,page:"/api/prestations",pathname:"/api/prestations",bundlePath:"",filename:""},userland:r})}};var t=require("../../webpack-api-runtime.js");t.C(e);var __webpack_exec__=e=>t(t.s=e),a=t.X(0,[4222,6541],()=>__webpack_exec__(885));module.exports=a})();