"use strict";(()=>{var e={};e.id=3598,e.ids=[3598],e.modules={145:e=>{e.exports=require("next/dist/compiled/next-server/pages-api.runtime.prod.js")},6027:(e,t,s)=>{s.r(t),s.d(t,{config:()=>c,default:()=>l,routeModule:()=>u});var a={};s.r(a),s.d(a,{default:()=>handler});var n=s(1802),r=s(7153),o=s(6249),i=s(6541);async function handler(e,t){if("GET"!==e.method)return t.status(405).json({error:"Method not allowed"});try{let e,s;let a=(0,i.getPool)();if(!a)return t.status(500).json({success:!1,error:"Database pool not initialized",details:"Failed to get database connection"});try{let[t]=await a.query(`
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' AND table_name = 'documents'
      `);e=t}catch(e){return console.error("Table check query error:",e.message),t.status(500).json({success:!1,error:"Failed to check if documents table exists",details:e.message})}let n=e&&e.length>0;if(!n)return t.status(200).json({success:!0,tableExists:!1,error:"Documents table does not exist",message:"Run migration 014 first - CREATE TABLE documents",recommendation:"Execute: sql/014_create_documents_table.sql"});try{let[e]=await a.query(`
        SELECT column_name, data_type 
        FROM information_schema.columns 
        WHERE table_name = 'documents'
        ORDER BY ordinal_position
      `);s=e}catch(e){return console.error("Columns check query error:",e.message),t.status(500).json({success:!1,error:"Failed to check table columns",details:e.message})}let r=["id","user_id","name","type","url","file_size","validation_status","created_at"],o=s&&s.length>0?s.map(e=>e.column_name):[],l=r.filter(e=>!o.includes(e)),c=o.includes("validation_status"),u=o.includes("validated_at");return t.status(200).json({success:!0,tableExists:!0,totalColumns:s?s.length:0,columns:s||[],requiredColumns:r,existingColumns:o,missingColumns:l.length>0?l:[],hasValidationStatus:c,hasValidatedAt:u,diagnosisOk:0===l.length&&c&&u,recommendation:c?"✅ All required columns present - upload should work":"❌ Missing validation columns - Run migration 015"})}catch(e){return console.error("Diagnosis error:",e),t.status(500).json({success:!1,error:"Database diagnostic failed",details:e.message||"Unknown error",type:e.name})}}let l=(0,o.l)(a,"default"),c=(0,o.l)(a,"config"),u=new n.PagesAPIRouteModule({definition:{kind:r.x.PAGES_API,page:"/api/admin/documents/check",pathname:"/api/admin/documents/check",bundlePath:"",filename:""},userland:a})}};var t=require("../../../../webpack-api-runtime.js");t.C(e);var __webpack_exec__=e=>t(t.s=e),s=t.X(0,[4222,6541],()=>__webpack_exec__(6027));module.exports=s})();