"use strict";(()=>{var e={};e.id=1938,e.ids=[1938],e.modules={145:e=>{e.exports=require("next/dist/compiled/next-server/pages-api.runtime.prod.js")},5184:e=>{e.exports=require("nodemailer")},6113:e=>{e.exports=require("crypto")},2459:(e,a,i)=>{i.r(a),i.d(a,{config:()=>u,default:()=>m,routeModule:()=>p});var t={};i.r(t),i.d(t,{default:()=>handler});var r=i(1802),s=i(7153),n=i(6249);let{query:o}=i(6541),l=i(6113),d=i(6271);async function handler(e,a){if("POST"!==e.method)return a.status(405).json({error:"Method not allowed"});try{let e=process.env.EBRIGADE_URL||"http://127.0.0.1/ebrigade",i=process.env.EBRIGADE_TOKEN;if(console.log("DEBUG: ebrigadeUrl =",e),console.log("DEBUG: ebrigadeToken =",i?"SET":"NOT SET"),!i)return console.error("ERROR: EBRIGADE_TOKEN not configured"),a.status(500).json({error:"EBRIGADE_TOKEN not configured"});let t=`${e.replace(/\/$/,"")}/api/export/search.php`,r={token:i,lastname:"%",qstrict:"0"};console.log("DEBUG: searchUrl =",t),console.log("DEBUG: searchBody =",JSON.stringify(r,null,2));let s=await fetch(t,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(r)});if(console.log("DEBUG: ebrigadeResponse.status =",s.status),console.log("DEBUG: ebrigadeResponse.ok =",s.ok),!s.ok){let e=await s.text();return console.error("eBrigade search failed:",s.status,e),a.status(502).json({error:"eBrigade search failed",statusCode:s.status,details:e.substring(0,200)})}let n=await s.json();console.log("DEBUG: ebrigadeData type =",typeof n,"isArray =",Array.isArray(n)),console.log("DEBUG: ebrigadeData length =",Array.isArray(n)?n.length:"N/A");let m=Array.isArray(n)?n:n.remote?n.remote:[],u=l.randomBytes(16).toString("hex"),p=[],c=[],g=[],_=[],h=[];for(let e of m){let a={original:e,ebrigadeId:String(e.id||e.ebrigade_id||e.EBR_ID||""),email:(e.email||"").toLowerCase().trim(),firstName:(e.firstname||e.first_name||"").trim(),lastName:(e.lastname||e.last_name||"").trim(),grade:(e.grade||e.fonction||e.role_label||"UNKNOWN").toUpperCase()};a.ebrigadeId&&a.email&&a.firstName&&a.lastName?h.push(a):_.push({id:a.ebrigadeId||"UNKNOWN",grade:a.grade,reason:a.email?"missing_name":"missing_email"})}let f=new Set,E=new Map;if(h.length>0){let e=h.map(e=>e.ebrigadeId),a=h.map(e=>e.email),i=await o(`SELECT id, email, liaison_ebrigade_id FROM users 
         WHERE liaison_ebrigade_id = ANY($1) OR email = ANY($2)`,[e,a]);i.rows.forEach(e=>{e.liaison_ebrigade_id&&f.add(e.liaison_ebrigade_id),E.set(e.email,e.id)})}let x=new Set,b=h.filter(e=>!f.has(e.ebrigadeId)&&E.has(e.email)).map(e=>e.email);if(b.length>0){let e=await o("SELECT id, email FROM users WHERE email = ANY($1) AND liaison_ebrigade_id IS NULL",[b]);e.rows.forEach(e=>x.add(e.email))}for(let e of h){let{original:a,ebrigadeId:i,email:t,firstName:r,lastName:s}=e;if(f.has(i)){c.push({email:t,firstName:r,lastName:s,ebrigadeId:i,status:"already_linked"});continue}if(x.has(t)){await o("UPDATE users SET liaison_ebrigade_id = $1 WHERE email = $2",[i,t]),c.push({email:t,firstName:r,lastName:s,ebrigadeId:i,status:"linked_existing"});continue}if(E.has(t)){c.push({email:t,firstName:r,lastName:s,ebrigadeId:i,status:"email_conflict"});continue}let n=l.randomBytes(32).toString("hex"),d=new Date(Date.now()+6048e5),m=await o(`INSERT INTO users (email, first_name, last_name, liaison_ebrigade_id, onboarding_status, 
         invitation_token, invitation_sent_at, invitation_expires_at, import_batch_id, is_active)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
         RETURNING id, email, first_name, last_name`,[t,r,s,i,"pending_signup",n,new Date,d,u,1]),g=m.rows[0];p.push({id:g.id,email:g.email,first_name:g.first_name,last_name:g.last_name,ebrigadeId:i,invitationToken:n})}let v=[],y=process.env.NEXT_PUBLIC_APP_URL||process.env.NEXT_PUBLIC_API_URL||"http://localhost:3000";for(let e of p)try{let a=`${y}/signup?token=${encodeURIComponent(e.invitationToken)}`,i=`
Bienvenue,

Vous avez \xe9t\xe9 d\xe9tect\xe9 dans la base eBrigade et une invitation \xe0 rejoindre notre plateforme vous a \xe9t\xe9 envoy\xe9e.

Cliquez sur le lien ci-dessous pour compl\xe9ter votre profil:

${a}

Ce lien est valide pendant 7 jours.

Cordialement,
L'\xe9quipe d'administration
        `;await d.send({to:e.email,subject:"Invitation \xe0 compl\xe9ter votre profil",text:i,html:`<p>Bienvenue,</p>
<p>Vous avez \xe9t\xe9 d\xe9tect\xe9 dans la base eBrigade et une invitation \xe0 rejoindre notre plateforme vous a \xe9t\xe9 envoy\xe9e.</p>
<p><a href="${a}">Cliquez ici pour compl\xe9ter votre profil</a></p>
<p>Ce lien est valide pendant 7 jours.</p>
<p>Cordialement,<br>L'\xe9quipe d'administration</p>`}),v.push({email:e.email,success:!0})}catch(a){console.error(`Failed to send email to ${e.email}:`,a),v.push({email:e.email,success:!1,error:a.message})}let N=v.filter(e=>e.success).length;a.status(200).json({batchId:u,summary:{totalEbrigadeUsers:m.length,processedUsers:h.length,created:p.length,alreadyLinked:c.length,emailsSent:N,emailsFailed:p.length-N,skippedDueToMissingData:_.length,errors:g.length},created:p,alreadyLinked:c,skippedUsers:_.slice(0,10),emailResults:v,errors:g.slice(0,10)})}catch(e){return console.error("eBrigade sync error:",e),a.status(500).json({error:"Failed to sync eBrigade users",details:e.message})}}let m=(0,n.l)(t,"default"),u=(0,n.l)(t,"config"),p=new r.PagesAPIRouteModule({definition:{kind:s.x.PAGES_API,page:"/api/admin/users/ebrigade-sync",pathname:"/api/admin/users/ebrigade-sync",bundlePath:"",filename:""},userland:t})}};var a=require("../../../../webpack-api-runtime.js");a.C(e);var __webpack_exec__=e=>a(a.s=e),i=a.X(0,[4222,6541,6271],()=>__webpack_exec__(2459));module.exports=i})();