"use strict";(()=>{var e={};e.id=3908,e.ids=[3908],e.modules={8432:e=>{e.exports=require("bcryptjs")},145:e=>{e.exports=require("next/dist/compiled/next-server/pages-api.runtime.prod.js")},964:(e,r,i)=>{i.r(r),i.d(r,{config:()=>d,default:()=>u,routeModule:()=>c});var a={};i.r(a),i.d(a,{default:()=>handler});var l=i(1802),o=i(7153),t=i(6249),s=i(3181),n=i(6541);async function handler(e,r){if(console.log("[api/login] handler start",e.method),"POST"!==e.method)return r.status(405).json({error:"Method not allowed"});let{email:i,password:a}=e.body||{};if(!i||!a)return r.status(400).json({error:"Email and password required"});try{console.log("[api/login] verifying user",i);let e=await (0,s.verifyUser)(String(i).trim().toLowerCase(),a);if(console.log("[api/login] verifyUser returned",!!e),!e)return r.status(401).json({error:"Invalid credentials"});let l=[];try{let r=await (0,n.query)("SELECT r.name FROM roles r JOIN user_roles ur ON ur.role_id = r.id WHERE ur.user_id = ?",[e.id]);Array.isArray(r)&&r.length>0&&(l=r.map(e=>e.name),console.log("[api/login] loaded",l.length,"roles from user_roles"))}catch(e){console.warn("[api/login] roles lookup failed (expected if migration not run yet), falling back to users.role:",e.message),l=[]}let o=l.length>0?l.join(","):e.role||"user";console.log("[api/login] raw role value:",o);let t=String(o).split(/[,;\s]+/).map(e=>(e||"").trim()).filter(e=>e.length>0);console.log("[api/login] role parts after split:",t);let u=Array.from(new Set(t.map(e=>{let r=(e||"").toString().toLowerCase().trim();return r?r.includes("infi")||r.includes("infirm")?"INFI":r.includes("med")?"MED":"admin"===r?"admin":"comptabilite"===r||r.includes("comptab")?"comptabilite":r.includes("moder")?"moderator":("user"===r||console.warn("[api/login] unrecognized role:",e,"-> defaulting to user"),"user"):null}).filter(e=>null!==e)));console.log("[api/login] normalized roles:",u);let d=u.length>0?u[0]:"user";return console.log("[api/login] active role:",d),r.status(200).json({token:"dev-token-"+Math.random().toString(36).slice(2,10),role:d,roles:u,email:e.email,message:"Login successful"})}catch(e){return console.error("[api/login] error:",e),r.status(500).json({error:e.message||"Server error"})}}let u=(0,t.l)(a,"default"),d=(0,t.l)(a,"config"),c=new l.PagesAPIRouteModule({definition:{kind:o.x.PAGES_API,page:"/api/auth/login",pathname:"/api/auth/login",bundlePath:"",filename:""},userland:a})},3181:(e,r,i)=>{let{getPool:a}=i(6541),l=i(8432);async function ensureUsersTable(){let e=a();await e.query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(255) NOT NULL UNIQUE,
      password_hash VARCHAR(255) NOT NULL,
      role VARCHAR(50) NOT NULL DEFAULT 'user',
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
  `)}async function createUser({email:e,password:r,role:i="user"}){let o=a(),t=(e||"").toLowerCase(),[s]=await o.query("SELECT id FROM users WHERE email = ?",[t]);if(s&&s.length>0)throw Error("User already exists");let n=await l.hash(r,10),u=(i||"user").toString(),d=u.toLowerCase();u=d.includes("infi")||d.includes("infirm")?"INFI":d.includes("med")?"MED":"admin"===d?"admin":"user";let[c]=await o.query("INSERT INTO users (email, password_hash, role) VALUES (?, ?, ?)",[t,n,u]);return{id:c.insertId,email:t,role:u}}async function verifyUser(e,r){let i=a(),o=(e||"").toLowerCase(),[t]=await i.query("SELECT id, email, password_hash, role FROM users WHERE email = ?",[o]);if(!t||0===t.length)return null;let s=t[0],n=await l.compare(r,s.password_hash);return n?{id:s.id,email:s.email,role:s.role}:null}async function findUserByEmail(e){let r=a(),i=(e||"").toLowerCase(),[l]=await r.query("SELECT id, email, role FROM users WHERE email = ?",[i]);return l&&0!==l.length?l[0]:null}e.exports={ensureUsersTable,createUser,verifyUser,findUserByEmail}}};var r=require("../../../webpack-api-runtime.js");r.C(e);var __webpack_exec__=e=>r(r.s=e),i=r.X(0,[4222,6541],()=>__webpack_exec__(964));module.exports=i})();